-- Add new columns to compras_pedidos for enhanced functionality
ALTER TABLE public.compras_pedidos 
ADD COLUMN IF NOT EXISTS desconto_centavos integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS forma_pagamento_id integer REFERENCES public.formas_pagamento(id),
ADD COLUMN IF NOT EXISTS negociacao text,
ADD COLUMN IF NOT EXISTS condicoes_pagamento text;

-- Create junction table for pedido-marca relationship (one supplier can have multiple brands)
CREATE TABLE IF NOT EXISTS public.compras_pedido_marcas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id integer REFERENCES public.compras_pedidos(id) ON DELETE CASCADE,
  marca_id integer REFERENCES public.marcas(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(pedido_id, marca_id)
);

-- Enable RLS on the new table
ALTER TABLE public.compras_pedido_marcas ENABLE ROW LEVEL SECURITY;

-- Create public access policy for compras_pedido_marcas
CREATE POLICY "Acesso público compras_pedido_marcas" 
ON public.compras_pedido_marcas 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- Add file_name and file_size columns to anexos for better file management
ALTER TABLE public.compras_pedido_anexos 
ADD COLUMN IF NOT EXISTS nome_arquivo text,
ADD COLUMN IF NOT EXISTS tamanho_bytes bigint,
ADD COLUMN IF NOT EXISTS storage_path text;

-- Create storage bucket for purchase order attachments
INSERT INTO storage.buckets (id, name, public) 
VALUES ('compras-anexos', 'compras-anexos', true)
ON CONFLICT (id) DO NOTHING;

-- Create storage policies for the bucket
CREATE POLICY "Public read access for compras-anexos"
ON storage.objects FOR SELECT
USING (bucket_id = 'compras-anexos');

CREATE POLICY "Public insert access for compras-anexos"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'compras-anexos');

CREATE POLICY "Public update access for compras-anexos"
ON storage.objects FOR UPDATE
USING (bucket_id = 'compras-anexos');

CREATE POLICY "Public delete access for compras-anexos"
ON storage.objects FOR DELETE
USING (bucket_id = 'compras-anexos');